package poo15;

public class TesteExcecao {

	public static void main(String[] args) {
		// tratando erros de excessão

		try {
			System.out.println("Valor do parametro que foi enviado: " + args[0]);
		} catch (Exception erro) {
			System.out.println("Erro encontrado !");
		}

	}

}
